/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment1_ct417;
import org.joda.time.*;
import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.*;

class StudentTest {
	
	Student student;
	StudentTest() {
		this.student = new Student("Luke Canny", new LocalDate(2001, 2,20), "CT");
	}
	
	@Test
	void objectCreated() {
		assertTrue(student instanceof Student, "Object Created");
	}
	
	@Test 
	void getStudentName() {
		assertEquals("Luke Canny", student.getName(), "Name matches");
	}
	
	@Test
	void getUsername() {
		assertEquals("LukeC21", student.getUsername(), "Username matches");
	}
	
	@Test
	void getDateOfBirth() {
		assertEquals(new LocalDate(2001,2,20), student.getDateOfBirth(), "Birthday matches");
	}
}
