/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment1_ct417;
import org.joda.time.*;
import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.*;

class StudentTest {
	
	Student student = new Student("Luke Canny", new LocalDate(2001, 2,20), "CT");;
	
	@Test
	void objectCreated() {
		assertTrue(student instanceof Student, "Object Created");
	}
	
	@Test 
	void getStudentName() {
		assertEquals("Luke Canny", student.getName(), "Name matches");
	}
	
	@Test
	void getUsername() {
		assertEquals("LukeC21", student.getUsername(), "Username matches");
	}
	
	@Test
	void getDateOfBirth() {
		assertEquals(new LocalDate(2001,2,20), student.getDateOfBirth(), "Birthday matches");
	}
	
//	@Test
//	void getID() {
//		assertEquals(1, student.getID(), "Student ID should be 1 as first user generated");
//	}
	
	@Test
	void getAge() {
		assertEquals(21, student.getAge(), "Student should be 21");
	}
}
